node {
  stage('deploy') {
    // Set the working directory to the application directory
    dir('/home/blockchain/backend/server') {
      // Pull the latest changes from the Git repository
      sh 'git pull'

      // Restart the PM2 process with the given name
      sh 'pm2 restart myapp'
    }
  }
}
