pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Perform the build steps here
                sh 'npm install'
            }
        }
        stage('Deploy') {
            steps {
                sh './deploy.sh'
            }
        }
    }
}
